apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:18.04
    command: ["bash"]
    #args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure