apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    purpose: demonstrate-command
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
  - name: ubuntu-container
    image: ubuntu:18.04
    volumeMounts:
    - name: shared-data
      mountPath: /bin/
  restartPolicy: OnFailure